[versions]
compileSdk = "33"
minSdk = "21"

coroutine = "1.6.4"

kotlin = "1.8.10"

squareup-okhttp = "4.10.0"
squareup-retrofit = "2.9.0"

[libraries]
android-plugin = { module = "com.android.tools.build:gradle", version = "7.4.2" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.10.0" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.5.2" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.7.0" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2023.04.00" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

coil-compose = "io.coil-kt:coil-compose:2.3.0"

compose-compiler = { module = "org.jetbrains.compose.compiler:compiler", version = "1.4.2" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version = "1.4.0" }
compose-rx2 = { module = "androidx.compose.runtime:runtime-rxjava2", version = "1.4.1" }

dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.8.10" }

buildConfig-plugin = "com.github.gmazzo:gradle-buildconfig-plugin:3.1.0"

junit = { module = "junit:junit", version = "4.13.2" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutine" }

maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.25.1" }

rx2 = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }

spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.18.0" }
squareup-okhttp-client = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okhttp" }
squareup-okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "squareup-okhttp" }
squareup-retrofit-client = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareup-retrofit" }
squareup-retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "squareup-retrofit" }
squareup-retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "squareup-retrofit" }

truth = { module = "com.google.truth:truth", version = "1.1.3" }
turbine = { module = "app.cash.turbine:turbine", version = "0.12.3" }
